
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Provider from '@/store/Provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cartify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider>
        <Header/>
        {children}
      </Provider>
      </body>
    </html>
  )
}
